# NumPy Arrays - Part 3<br>
NumPy - 대규모의 다차원 배열을 쉽게 처리할 때 사용하는 파이썬 라이브러리<br>

원본 출처: Introduction to Deep Learning at Carnegie Mellon University (https://deeplearning.cs.cmu.edu/S22/index.html)

In [ ]:
# Import the NumPy 
import numpy as np

## 1. 데이터 읽어오기

### a. 인덱싱: NumPy 배열에서 값 읽어오기

In [ ]:
# TODO: 무작위 값으로 채워진 4 x 5 x 6 배열을 만들어보세요. (5 x 6 행렬이 4개 묶음 있는 것으로 해석할 수 있음)
n = np.random.rand(4, 5, 6)
n.shape

(4, 5, 6)

나중에 다룰 MNIST (필기체 인식) 데이터셋의 모양은 (60000, 28, 28)인데
28 (행의 수, 높이) x 28 (열의 수, 너비)의 그림 60000만장이 있는 것으로 해석됩니다.

In [ ]:
# TODO: n에서 두 번째 묶음의 세 번째 행, 네 번째 열의 값은? (인덱스는 0에서 시작함)

n[1][2][3]

0.8865501143538694

### b. 슬라이싱: NumPy 배열의 일부를 가져오기

시작(포함):끝(미포함)으로 연속된 항목을 슬라이싱 <br>
:만 쓰면 전체

In [ ]:
# 첫 번째 묶음의 모든 행렬 가져오기
print(n[0, :, :]) # same as: n[0], 정답이므로 수정할 필요 없음

[[0.11218067 0.81369178 0.63976013 0.07801077 0.44327999 0.64064276]
 [0.36211845 0.95236874 0.65642402 0.65644194 0.02892639 0.34172087]
 [0.16343563 0.78942458 0.40348388 0.41319848 0.66749287 0.38485891]
 [0.62716834 0.32475821 0.60073983 0.26826515 0.56700069 0.72257279]
 [0.06723122 0.05169143 0.07296266 0.21252854 0.62560294 0.04256619]]


In [ ]:
# TODO: 첫 번째 묶음에서 [0, 3) 행, [0, 4) 열 가져오기, 즉 3 x 4 배열이 나와야 함
print(n[0, 0:3, 0:4])

[[0.11218067 0.81369178 0.63976013 0.07801077]
 [0.36211845 0.95236874 0.65642402 0.65644194]
 [0.16343563 0.78942458 0.40348388 0.41319848]]


In [ ]:
# TODO: 전체 묶음에서 4번 째 행, 5번째 열 값들 가져오기
print(n[:, 3, 4]) 

[0.04256619 0.87152407 0.59453908 0.3105967 ]


### c. Slicing at Interval
시작::증가폭(스텝)으로 띄엄띄엄 슬라이싱<br>
예) a[7::2]인 경우 a[7], a[9], a[11], ... 을 가져와서 배열로 만듦

In [ ]:
# TODO: 0번 묶음, 2번 묶음, 4번 묶음, ... 슬라이싱 (n은 3번 묶음까지만 있어서 두 개의 묶음만 출력됨)
print(n[0::2])

[[[0.11218067 0.81369178 0.63976013 0.07801077 0.44327999 0.64064276]
  [0.36211845 0.95236874 0.65642402 0.65644194 0.02892639 0.34172087]
  [0.16343563 0.78942458 0.40348388 0.41319848 0.66749287 0.38485891]
  [0.62716834 0.32475821 0.60073983 0.26826515 0.56700069 0.72257279]
  [0.06723122 0.05169143 0.07296266 0.21252854 0.62560294 0.04256619]]

 [[0.18638325 0.46867517 0.96248602 0.68070032 0.35796108 0.58190338]
  [0.0373244  0.9061857  0.61219042 0.75650068 0.38091321 0.88304438]
  [0.97881229 0.03786187 0.2002956  0.84916913 0.45753409 0.47099201]
  [0.1896326  0.02506162 0.87668185 0.64149075 0.07499497 0.03432431]
  [0.35600909 0.99955961 0.68240351 0.89631386 0.96132894 0.59453908]]]


원래 n의 모습과 비교해가며 아래의 결과는 어떻게 만들어진 것인지 이해하고 넘어가세요.

In [ ]:
print(n[0::2, 1:4, 1::2]) 

[[[0.95236874 0.65644194 0.34172087]
  [0.78942458 0.41319848 0.38485891]
  [0.32475821 0.26826515 0.72257279]]

 [[0.9061857  0.75650068 0.88304438]
  [0.03786187 0.84916913 0.47099201]
  [0.02506162 0.64149075 0.03432431]]]


## 2. 데이터 수정하기

In [ ]:
# 배열 복사하기
n_copy = np.copy(n)

### a. 하나의 값 수정하기

In [ ]:
# 복사한 배열과 n이 같은지 하나의 항목 확인
print(n_copy[2, 4, 1] == n[2, 4, 1])

True


In [ ]:
# TODO: 복사한 배열 n_copy[2, 4, 1]의 값을 0.005로 변경
n_copy[2, 4, 1] = 0.005

# 여전히 내용이 같은지 확인
print(n_copy[2, 4, 1] == n[2, 4, 1])

False


n_copy는 n을 복사한 것이지만 n과 다른 위치에 독립적으로 존재한다. 만약 copy 함수로 복사하지 않고 m = n으로 m을 만든다음 m[2, 4, 1] 값을 수정하면 어떻게 될까? 

In [ ]:
print('Before: ', n[2, 4, 1])
m = n
m[2, 4, 1] = 0.5
print('After: ', n[2, 4, 1])

Before:  0.9995596095263243
After:  0.5


In [ ]:
# n, m, n_copy가 저장된 장소 출력
print(id(n))
print(id(m))
print(id(n_copy))

140407172087408
140407172087408
140407172086352


### b. 여러 항목의 값을 같은 값으로 수정하기

In [ ]:
n_copy = np.copy(n)

# n_copy 3번째 묶음의 4번째 행의 값 확인
print(n_copy[2, 3])

[0.1896326  0.02506162 0.87668185 0.64149075 0.07499497 0.03432431]


In [ ]:
# TODO: n_copy 3번째 묶음, 4번째 행의 값을 모두 0.5로 바꾸기
n_copy[2, 3] = 0.5

# n_copy 3번째 묶음의 4번째 열의 값 확인
print(n_copy[2, 3])

[0.5 0.5 0.5 0.5 0.5 0.5]
