# NumPy Arrays - Part 4<br>

by uramoon@kw.ac.kr<br>
원본 출처: Introduction to Deep Learning at Carnegie Mellon University (https://deeplearning.cs.cmu.edu/S22/index.html)

In [ ]:
# Import the NumPy 
import numpy as np

## Reshaping Arrays (배열의 모양을 다르게 해석하기)<br>

Array reshaping은 배열안의 데이터는 그대로 두고 모양을 바꿔 해석을 다르게 하는 것입니다.

예를 들어 (4,) 모양의 1차원 배열 [1, 2, 3, 4]는 (4, 1) 모양의 2차원 배열 [[1], [2], [3], [4]], <br> 또는 (2, 2) 모양의 2차원 배열 [[1, 2], [3, 4]] 및 (1, 4) 모양의 2차원 배열 [[1, 2, 3, 4]]로 형태를 바꿔 해석할 수도 있습니다.

### 동일 차원으로 reshaping

In [ ]:
s = np.random.rand(3, 4, 5)
print(f"원래 모양: {s.shape}")

원래 모양: (3, 4, 5)


***TODO: s의 전체 원소 개수 구하기***
* Q: 어떻게 계산할 수 있을까요?
* A: (수식을 기재하세요.) d0 X d1 X d2 = 3 X 4 X 5 = 60

In [ ]:
s.size

60

In [ ]:
# s 내용 확인하기
print(s)

[[[0.75675711 0.43523807 0.78537989 0.36636849 0.3489614 ]
  [0.23586638 0.07171624 0.56911117 0.11212976 0.34805235]
  [0.92979425 0.79982078 0.28561957 0.90782656 0.58473826]
  [0.9680355  0.17546026 0.50534846 0.02382291 0.16727903]]

 [[0.73745093 0.4614811  0.4269527  0.0590955  0.97531481]
  [0.10299795 0.48067335 0.26791782 0.36916629 0.11770086]
  [0.61265794 0.0475829  0.47077338 0.77519871 0.56622933]
  [0.27025959 0.42797707 0.73606897 0.49310861 0.79250385]]

 [[0.88806556 0.01774582 0.71277275 0.3161543  0.38421733]
  [0.1832596  0.58859275 0.07421957 0.8548491  0.95961168]
  [0.36943196 0.77103679 0.96711907 0.29198366 0.53266347]
  [0.9974477  0.30723008 0.49463768 0.65214169 0.22270975]]]


In [ ]:
# TODO: s를 (2, 6, 5)로 reshape하여 s1에 저장하기
s1 = s.reshape(2, 6, 5)
print(f"s1의 모양: {s1.shape}")

s1의 모양: (2, 6, 5)


In [ ]:
# s와 s1의 각 원소값과 위치는 동일한 것을 확인해보세요.
print(s1)
print(s.shape, s1.shape, s.shape == s1.shape)

[[[0.75675711 0.43523807 0.78537989 0.36636849 0.3489614 ]
  [0.23586638 0.07171624 0.56911117 0.11212976 0.34805235]
  [0.92979425 0.79982078 0.28561957 0.90782656 0.58473826]
  [0.9680355  0.17546026 0.50534846 0.02382291 0.16727903]
  [0.73745093 0.4614811  0.4269527  0.0590955  0.97531481]
  [0.10299795 0.48067335 0.26791782 0.36916629 0.11770086]]

 [[0.61265794 0.0475829  0.47077338 0.77519871 0.56622933]
  [0.27025959 0.42797707 0.73606897 0.49310861 0.79250385]
  [0.88806556 0.01774582 0.71277275 0.3161543  0.38421733]
  [0.1832596  0.58859275 0.07421957 0.8548491  0.95961168]
  [0.36943196 0.77103679 0.96711907 0.29198366 0.53266347]
  [0.9974477  0.30723008 0.49463768 0.65214169 0.22270975]]]
(3, 4, 5) (2, 6, 5) False


### 다른 차원으로 reshaping

In [ ]:
# TODO: 0부터 119까지 120개의 정수로 이루어진 1차원 배열을 간단하게 만들어보세요.
r = np.arange(0, 120)

r

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [ ]:
print(f"원래 모양: {r.shape}")

원래 모양: (120,)


In [ ]:
# TODO: (120,) -> (3, 4, 10)
# 원소개수는 120개로 동일합니다.
r1 = np.reshape(r, (3, 4, 10))
print(f"r1의 모양: {r1.shape}")

r1의 모양: (3, 4, 10)


In [ ]:
# r과 r1을 비교해보세요.
print(r)
print(r1)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 1

In [ ]:
# TODO: r1을 reshape하여 r2에 저장하세요.
# (3, 4, 10) -> (6, 20)
r2 = np.reshape(r1, (6, 20))
print(f"r2의 모양: {r2.shape}")

r2의 모양: (6, 20)


In [ ]:
# r2와 r1, r을 비교해보세요.
print(r1)
print(r2)

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]]
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109

## 배열 펼치기 (Flattening)
배열 펼치기는 다차원 배열을 일차원으로 만들어줍니다.<br>
일반적인 다층 퍼셉트론 인공 신경망은 일차원 배열을 입력으로 받기 때문에<br> MNIST 데이터셋을 사용하면 28 x 28 2차원 배열을 길이 784의 일차원 배열로 만들어 사용합니다.

In [ ]:
k = np.random.rand(5, 6)
k

array([[0.54129088, 0.9378641 , 0.04490721, 0.19410967, 0.70301852,
        0.30301207],
       [0.03196256, 0.94482394, 0.16094205, 0.74361722, 0.76647969,
        0.79896882],
       [0.45883133, 0.25633355, 0.30013433, 0.81903709, 0.23384803,
        0.62720591],
       [0.004181  , 0.98075087, 0.71089152, 0.96218694, 0.78373382,
        0.54352463],
       [0.80296108, 0.42093665, 0.94028802, 0.09740142, 0.67911714,
        0.08993501]])

### 기본 순서대로 펼치기

In [ ]:
# k와 k1을 비교해보세요.
k1 = k.flatten() 
k1

array([0.54129088, 0.9378641 , 0.04490721, 0.19410967, 0.70301852,
       0.30301207, 0.03196256, 0.94482394, 0.16094205, 0.74361722,
       0.76647969, 0.79896882, 0.45883133, 0.25633355, 0.30013433,
       0.81903709, 0.23384803, 0.62720591, 0.004181  , 0.98075087,
       0.71089152, 0.96218694, 0.78373382, 0.54352463, 0.80296108,
       0.42093665, 0.94028802, 0.09740142, 0.67911714, 0.08993501])

In [ ]:
k1.shape

(30,)

## 배열 이어 붙이기
https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# 2차원 배열인 array1과 array2 생성
array1 = np.array([[1, 2], [3, 4]])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([[5, 6]])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

Array 1 is 
 [[1 2]
 [3 4]]  with dimensions  (2, 2) 

Array 2 is 
 [[5 6]]  with dimensions  (1, 2) 



배열을 이어붙일 때에는 기준이 되는 축 이외에 모양이 동일해야 합니다.<br>
1. (2, 2)와 (1, 2) 이어 붙일 때 0번 인덱스로 이어붙이면 (3, 2) 배열 탄생
2. (2, 2)와 (1, 2) 이어 붙일 때 1번 인덱스로 이어붙이면 0번 인덱스의 모양이 서로 다르므로 이어붙이기 실패

In [ ]:
# TODO: 0번 인덱스를 기준으로 array1과 array2를 이어붙이세요.
concatenated_array1 = np.concatenate((array1, array2), axis=0)
print("Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is \n", concatenated_array1, "with dimensions ", concatenated_array1.shape, '\n')

Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is 
 [[1 2]
 [3 4]
 [5 6]] with dimensions  (3, 2) 



In [ ]:
# TODO: 1번 인덱스를 기준으로 array1과 array2를 이어붙이세요. (실패합니다. 에러 메시지를 확인하세요.)
concatenated_array2 = np.concatenate((array1, array2), axis=1)
print("Concatenated array 2 along axis 0 (column-wise for 2-d arrays) is \n", concatenated_array2, "with dimensions ", concatenated_array2.shape)

ValueError: ignored

In [ ]:
# TODO: (3, 4, 5) 형태에 3 미만의 무작위 정수로 채워진 배열을 만드세요.
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html
array1 = np.random.randint(3, size=(3, 4, 5))
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

Array 1 is 
 [[[2 0 1 0 2]
  [0 2 1 1 0]
  [1 0 1 2 1]
  [1 2 0 1 0]]

 [[1 1 2 0 2]
  [2 0 2 0 2]
  [2 1 0 2 0]
  [0 1 1 1 0]]

 [[1 2 0 0 0]
  [2 1 2 0 1]
  [1 0 0 0 0]
  [2 1 1 1 1]]]  with dimensions  (3, 4, 5) 



In [ ]:
# TODO: (3, 4, 5) 형태에 4 미만의 무작위 정수로 채워진 배열을 만드세요.
array2 = np.random.randint(4, size=(3, 4, 5))
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

Array 2 is 
 [[[3 0 0 0 2]
  [1 0 3 3 0]
  [0 2 3 0 3]
  [0 1 2 3 0]]

 [[2 2 2 0 2]
  [0 3 2 3 3]
  [2 1 0 3 3]
  [3 0 0 0 0]]

 [[0 0 3 3 3]
  [3 1 3 0 1]
  [1 0 2 0 3]
  [0 3 2 1 3]]]  with dimensions  (3, 4, 5) 



***TODO: 0번 인덱스를 기준으로 이어붙이기***
* Q: 어떤 모양일까요? (코딩으로 결과 확인 전에 작성해보세요.)
* A: axis=0 (index)을 기준으로 합치는 것이기 때문에 (6, 4, 5) 라고 생각합니다.

In [ ]:
# TODO: 0번 인덱스를 기준으로 이어붙이기
concatenated_array1 = np.concatenate((array1, array2), axis=0)
print("Concatenated array 1 is \n", concatenated_array1, "\n\n", "and the dimensions of the concatenated array 1 are: \n", concatenated_array1.shape)

Concatenated array 1 is 
 [[[2 0 1 0 2]
  [0 2 1 1 0]
  [1 0 1 2 1]
  [1 2 0 1 0]]

 [[1 1 2 0 2]
  [2 0 2 0 2]
  [2 1 0 2 0]
  [0 1 1 1 0]]

 [[1 2 0 0 0]
  [2 1 2 0 1]
  [1 0 0 0 0]
  [2 1 1 1 1]]

 [[3 0 0 0 2]
  [1 0 3 3 0]
  [0 2 3 0 3]
  [0 1 2 3 0]]

 [[2 2 2 0 2]
  [0 3 2 3 3]
  [2 1 0 3 3]
  [3 0 0 0 0]]

 [[0 0 3 3 3]
  [3 1 3 0 1]
  [1 0 2 0 3]
  [0 3 2 1 3]]] 

 and the dimensions of the concatenated array 1 are: 
 (6, 4, 5)


***TODO: 1번 인덱스를 기준으로 이어붙이기***
* Q: 어떤 모양일까요? (코딩으로 결과 확인 전에 작성해보세요.)
* A: axis=1 (index)을 기준으로 합치는 것이기 때문에 (3, 8, 5) 라고 생각합니다.

In [ ]:
# TODO: 1번 인덱스를 기준으로 이어붙이기
concatenated_array2 = np.concatenate((array1, array2), axis=1)
print("Concatenated array 2 is \n", concatenated_array2, "\n\n", "and the dimensions of the concatenated array 2 are: \n", concatenated_array2.shape)

Concatenated array 2 is 
 [[[2 0 1 0 2]
  [0 2 1 1 0]
  [1 0 1 2 1]
  [1 2 0 1 0]
  [3 0 0 0 2]
  [1 0 3 3 0]
  [0 2 3 0 3]
  [0 1 2 3 0]]

 [[1 1 2 0 2]
  [2 0 2 0 2]
  [2 1 0 2 0]
  [0 1 1 1 0]
  [2 2 2 0 2]
  [0 3 2 3 3]
  [2 1 0 3 3]
  [3 0 0 0 0]]

 [[1 2 0 0 0]
  [2 1 2 0 1]
  [1 0 0 0 0]
  [2 1 1 1 1]
  [0 0 3 3 3]
  [3 1 3 0 1]
  [1 0 2 0 3]
  [0 3 2 1 3]]] 

 and the dimensions of the concatenated array 2 are: 
 (3, 8, 5)


***TODO: 2번 인덱스를 기준으로 이어붙이기***
* Q: 어떤 모양일까요? (코딩으로 결과 확인 전에 작성해보세요.)
* A: axis=2 (index)을 기준으로 합치는 것이기 때문에 (3, 4, 10) 라고 생각합니다.

In [ ]:
# TODO: 2번 인덱스를 기준으로 이어붙이기
concatenated_array3 = np.concatenate((array1, array2), axis=2)
print("Concatenated array 3 is \n", concatenated_array3, "\n\n", "and the dimensions of the concatenated array 3 are: \n", concatenated_array3.shape)

Concatenated array 3 is 
 [[[2 0 1 0 2 3 0 0 0 2]
  [0 2 1 1 0 1 0 3 3 0]
  [1 0 1 2 1 0 2 3 0 3]
  [1 2 0 1 0 0 1 2 3 0]]

 [[1 1 2 0 2 2 2 2 0 2]
  [2 0 2 0 2 0 3 2 3 3]
  [2 1 0 2 0 2 1 0 3 3]
  [0 1 1 1 0 3 0 0 0 0]]

 [[1 2 0 0 0 0 0 3 3 3]
  [2 1 2 0 1 3 1 3 0 1]
  [1 0 0 0 0 1 0 2 0 3]
  [2 1 1 1 1 0 3 2 1 3]]] 

 and the dimensions of the concatenated array 3 are: 
 (3, 4, 10)
