# NumPy Arrays - Part 2<br>
NumPy - 대규모의 다차원 배열을 쉽게 처리할 때 사용하는 파이썬 라이브러리<br>

by uramoon@kw.ac.kr<br>
원본 출처: Introduction to Deep Learning at Carnegie Mellon University (https://deeplearning.cs.cmu.edu/S22/index.html)

In [ ]:
# Import the NumPy 
import numpy as np

## 0. 다차원 배열의 이해

In [ ]:
arr = np.array([1, 2, 3, 4])

# 1차원 배열
print(arr)

[1 2 3 4]


In [ ]:
# 2차원 배열로 해석하기
print(arr.reshape(4, 1))
print(arr.reshape(2, 2))
print(arr.reshape(1, 4))

[[1]
 [2]
 [3]
 [4]]
[[1 2]
 [3 4]]
[[1 2 3 4]]


***TODO: 어떻게 해석할 수 있을까요?***
1. arr.reshape(4, 1): 길이 1인 배열이 4 개가 있음. (4 by 1 행렬, 행:4개 열:1개)
2. arr.reshape(2, 2): 길이 2인 배열이 두 개 있음. (2 by 2 행렬, 행:2개 열:2개)
3. arr.reshape(1, 4): 길이 4인 배열이 한개 있음. (1 by 4 행렬, 행:1개 열:4개)

## 1. 배열 초기화



### a. 비어 있는 (초기화 안된) / 0으로 채워진 / 1로 채워진 / 특정 값으로 채워진 배열 만들기
1. numpy.empty (https://numpy.org/doc/stable/reference/generated/numpy.empty.html)
2. numpy.zeros (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros)
3. numpy.ones (https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones)
4. numpy.full (https://numpy.org/doc/stable/reference/generated/numpy.full.html#numpy.full)

In [ ]:
# 비어있는 2 x 2 배열 만들기
empty_arr = np.empty((2, 2))
print(empty_arr)

[[2.46204848e-316 0.00000000e+000]
 [1.09385187e-303 1.09385744e-303]]


***TODO: numpy.empty의 장점과 단점은 무엇일까요?***
* 장점: numpy.zeros, numpy.ones, numpy.ones와 달리 설정되어져서 반환되는 것이 아니므로 속도가 빠를 수 있다.
* 단점: 하지만 반환된 이후 내가 직접(수동적으로) 설정(코딩)을 해야한다. (manually set all the values in the array)

In [ ]:
# TODO: 모두 0으로 채워진 2 x 3 배열 만들기
zero_arr = np.zeros((2, 3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# TODO: 모두 1로 채워진 4 x 2 배열 만들기
ones_arr = np.ones((4, 2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# TODO: 모두 10으로 채워진 2 x 2 배열 만들기
tens_arr = np.full(shape=(2, 2), fill_value=10)
print(tens_arr)

[[10 10]
 [10 10]]


### b. 주어진 배열과 동일한 모양의 배열 만들기
1. numpy.zeros_like (https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html#numpy.zeros_like)
2. numpy.ones_like (https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html#numpy.ones_like)
3. numpy.full_like (https://numpy.org/doc/stable/reference/generated/numpy.full_like.html#numpy.full_like)

In [ ]:
# TODO: ones_arr과 동일한 모양에 0으로 채워진 배열 만들기
zeros_like_arr = np.zeros_like(ones_arr)
print(zeros_like_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# TODO: zeros_arr과 동일한 모양에 1로 채워진 배열 만들기
ones_like_arr = np.ones_like(zero_arr)
print(ones_like_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# TODO: zeros_arr과 동일한 모양에 0.1로 채워진 배열 만들기
full_like_arr = np.full_like(zero_arr, fill_value=0.1)
print(full_like_arr)

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


### c. 기존의 데이터로 배열 만들기
1. numpy.array (https://numpy.org/doc/stable/reference/generated/numpy.array.html)
2. numpy.loadtxt (https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html) (텍스트 파일에 저장했다 불러오기, 생략)
3. numpy.load (https://numpy.org/doc/stable/reference/generated/numpy.load.html) (.npy, .npz 등에 저장했다 불러오기, 생략)

In [ ]:
# TODO: new_list 리스트로 배열 만들기
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("An array from given list is \n", arr_from_list, " with dimensions ", arr_from_list.shape, "\n")

An array from given list is 
 [1 2 3 4]  with dimensions  (4,) 



### d. 주어진 숫자 범위에서 만들기
1. numpy.arange (https://numpy.org/doc/stable/reference/generated/numpy.arange.html)
2. numpy.linspace (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [ ]:
# TODO: 0부터 9까지 모든 정수를 담고 있는 배열 만들기
range_arr = np.arange(10)
print("An array given range is \n", range_arr, " with dimensions ", range_arr.shape, "\n")

An array given range is 
 [0 1 2 3 4 5 6 7 8 9]  with dimensions  (10,) 



In [ ]:
# TODO: 2부터 3까지 [2, 3) 동일 간격으로 다섯 개의 실수를 포함하는 배열 만들기 (2는 포함, 3은 미포함)
linspace_arr = np.linspace(2, 3, num=5)
print("An evenly spaced array given range is \n", linspace_arr, " with dimensions ", linspace_arr.shape, "\n")

An evenly spaced array given range is 
 [2.   2.25 2.5  2.75 3.  ]  with dimensions  (5,) 



### e. 무작위 값으로 채운 배열 만들기

1. numpy.random.rand (https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)
2. numpy.random.randint (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)
3. numpy.random.randn (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

In [ ]:
# TODO: [0, 1)에서 추출한 무작위 실수로 3 x 2 배열 만들기
uniform_rand_arr = np.random.rand(3, 2)
print("A random array from a uniform distribution is \n", uniform_rand_arr, " with dimensions ", uniform_rand_arr.shape, "\n")

A random array from a uniform distribution is 
 [[0.81645081 0.55684444]
 [0.09710767 0.65674462]
 [0.13525943 0.38919339]]  with dimensions  (3, 2) 



In [ ]:
# TODO: [0, 5)에서 추출한 무작위 정수로 2 x 4 배열 만들기
range_rand_int_arr = np.random.randint(5, size=(2,4))
print("A random integer array from a range is \n", range_rand_int_arr, " with dimensions ", range_rand_int_arr.shape, "\n")

A random integer array from a range is 
 [[0 1 1 2]
 [4 0 3 3]]  with dimensions  (2, 4) 



정규분포 $\mathcal{N}(\mu, \sigma^2)$에서 추출한 표본들로로 배열 만들 때:<br>
$\mu$ + $\sigma$ * np.random.randn(...) 

In [ ]:
# TODO: 평균: 3, 표준편차: 2.5인 정규분포에서 추출한 무작위 실수로 2 x 4 배열 만들기 
mu = 3
sigma = 2.5
sample_normal_arr = mu + sigma * np.random.randn(2, 4)
print("A random array from a gaussian distribution is \n", sample_normal_arr)
print("with mu: ", mu)
print("with sigma: ", sigma)
print("with dimensions ", sample_normal_arr.shape)

A random array from a gaussian distribution is 
 [[ 6.61466261  1.62832036  5.64600842  5.87757715]
 [-0.68844523  2.76488607  3.57663907  3.25337466]]
with mu:  3
with sigma:  2.5
with dimensions  (2, 4)
